
platform :ios, "9.0"
inhibit_all_warnings!
use_frameworks!

target 'DemoCode' do

    pod 'ReactiveObjC'
    pod 'AFNetworking'
    pod 'MJExtension'
    pod 'MJRefresh’
    pod 'Masonry'
    pod 'YYModel'
    pod 'YYCache'
    pod 'YYWebImage'
    pod 'HyCategoriess'
    pod 'KafkaRefresh'
    pod 'CocoaAsyncSocket'
    pod 'SocketRocket'
    
    pod 'GPUImage'

end
