
source 'https://github.com/hydreamit/Specs'
source 'https://cdn.cocoapods.org/'

platform :ios, "9.0"
inhibit_all_warnings!
use_frameworks!

target 'DemoCode' do

    pod 'HyBaseComponents'
    pod 'HyCategoriess'
    
    pod 'Masonry'
    pod 'YYWebImage'
  
    pod 'CocoaAsyncSocket'
    pod 'SocketRocket'
    
    pod 'GPUImage'
    pod 'LFPhoneInfo'

end
